class Autogenerated {
  int? statusCode;
  bool? success;
  List<String>? messages;
  List<Data>? data;
  

  Autogenerated({this.statusCode, this.success, this.messages, this.data});

  // CopyWith method
  Autogenerated copyWith({
    int? statusCode,
    bool? success,
    List<String>? messages,
    List<Data>? data,
  }) {
    return Autogenerated(
      statusCode: statusCode ?? this.statusCode,
      success: success ?? this.success,
      messages: messages ?? this.messages,
      data: data ?? this.data,
    );
  }

  // Initial method (returns a default/empty instance)
  static Autogenerated initial() {
    return Autogenerated(
      statusCode: 0,
      success: false,
      messages: [],
      data: [],
    );
  }

  Autogenerated.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode'];
    success = json['success'];
    messages = json['messages'].cast<String>();
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['statusCode'] = this.statusCode;
    data['success'] = this.success;
    data['messages'] = this.messages;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String? sId;
  String? userId;
  String? productId;
  String? productName;
  String? productDescription;
  int? price;
  String? category;
  String? createdAt;
  String? updatedAt;
  int? iV;

  Data(
      {this.sId,
      this.userId,
      this.productId,
      this.productName,
      this.productDescription,
      this.price,
      this.category,
      this.createdAt,
      this.updatedAt,
      this.iV});

  // CopyWith method
  Data copyWith({
    String? sId,
    String? userId,
    String? productId,
    String? productName,
    String? productDescription,
    int? price,
    String? category,
    String? createdAt,
    String? updatedAt,
    int? iV,
  }) {
    return Data(
      sId: sId ?? this.sId,
      userId: userId ?? this.userId,
      productId: productId ?? this.productId,
      productName: productName ?? this.productName,
      productDescription: productDescription ?? this.productDescription,
      price: price ?? this.price,
      category: category ?? this.category,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      iV: iV ?? this.iV,
    );
  }

  // Initial method (returns a default/empty instance)
  static Data initial() {
    return Data(
      sId: '',
      userId: '',
      productId: '',
      productName: '',
      productDescription: '',
      price: 0,
      category: '',
      createdAt: '',
      updatedAt: '',
      iV: 0,
    );
  }

  Data.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    userId = json['userId'];
    productId = json['productId'];
    productName = json['productName'];
    productDescription = json['productDescription'];
    price = json['price'];
    category = json['category'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['userId'] = this.userId;
    data['productId'] = this.productId;
    data['productName'] = this.productName;
    data['productDescription'] = this.productDescription;
    data['price'] = this.price;
    data['category'] = this.category;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['__v'] = this.iV;
    return data;
  }
}
