class Autogenerated {
  int? statusCode;
  bool? success;
  List<String>? messages;
  List<Data>? data;

  Autogenerated({this.statusCode, this.success, this.messages, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode'];
    success = json['success'];
    messages = json['messages'].cast<String>();
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    data['statusCode'] = this.statusCode;
    data['success'] = this.success;
    data['messages'] = this.messages;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }

  // CopyWith method
  Autogenerated copyWith({
    int? statusCode,
    bool? success,
    List<String>? messages,
    List<Data>? data,
  }) {
    return Autogenerated(
      statusCode: statusCode ?? this.statusCode,
      success: success ?? this.success,
      messages: messages ?? this.messages,
      data: data ?? this.data,
    );
  }

  // Initial method
  static Autogenerated initial() {
    return Autogenerated(
      statusCode: 0,
      success: false,
      messages: [],
      data: [],
    );
  }
}
class Data {
  String? sId;
  String? userId;
  String? productId;
  String? productName;
  String? productDescription;
  String? productImage;
  int? price;
  String? category;
  String? spareParts;

  Data({
    this.sId,
    this.userId,
    this.productId,
    this.productName,
    this.productDescription,
    this.productImage,
    this.price,
    this.category,
    this.spareParts,
  });

  Data.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    userId = json['userId'];
    productId = json['productId'];
    productName = json['productName'];
    productDescription = json['productDescription'];
    productImage = json['productImage'];
    price = json['price'];
    category = json['category'];
    spareParts = json['spareParts'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    data['_id'] = this.sId;
    data['userId'] = this.userId;
    data['productId'] = this.productId;
    data['productName'] = this.productName;
    data['productDescription'] = this.productDescription;
    data['productImage'] = this.productImage;
    data['price'] = this.price;
    data['category'] = this.category;
    data['spareParts'] = this.spareParts;
    return data;
  }

  // CopyWith method
  Data copyWith({
    String? sId,
    String? userId,
    String? productId,
    String? productName,
    String? productDescription,
    String? productImage,
    int? price,
    String? category,
    String? spareParts,
  }) {
    return Data(
      sId: sId ?? this.sId,
      userId: userId ?? this.userId,
      productId: productId ?? this.productId,
      productName: productName ?? this.productName,
      productDescription: productDescription ?? this.productDescription,
      productImage: productImage ?? this.productImage,
      price: price ?? this.price,
      category: category ?? this.category,
      spareParts: spareParts ?? this.spareParts,
    );
  }

  // Initial method
  static Data initial() {
    return Data(
      sId: '',
      userId: '',
      productId: '',
      productName: '',
      productDescription: '',
      productImage: '',
      price: 0,
      category: '',
      spareParts: '',
    );
  }
}
